version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ducklake
      POSTGRES_PASSWORD: ducklake
      POSTGRES_DB: ducklake
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console UI
    volumes:
      - ./minio-data:/data

  minio_setup:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: ["/bin/sh", "-c", "/init/init-minio.sh"]
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_USER: dagster
      MINIO_PASSWORD: dagster123
    volumes:
      - ./init:/init

  dagster:
    build: ./dagster
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    volumes:
      - ./dagster:/opt/dagster
      - ./dagster/dagster_home:/opt/dagster/dagster_home
      - ./dagster/var:/var 
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - minio

  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - ./semantic_layer:/cube/conf

volumes:
  pgdata:
  # TODO: figure out other volumes I want to include
